pipeline {
    agent any

    stages {
        stage('Build Java') {
            steps {
                dir('backend') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Run Java') {
            steps {
                dir('backend') {
                    sh 'mvn exec:java'
                }
            }
        }

        stage('Install Node.js Packages') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }

        stage('Run Node.js App') {
            steps {
                dir('frontend') {
                    sh 'npm start'
                }
            }
        }
    }
}
