pipeline {
    agent any

    tools {
        maven 'Maven 3.26 '        // Set up this tool in Jenkins
        nodejs 'NodeJS 1.6.5'     // Also set up in Jenkins
    }

    stages {
        stage('Build Java') {
            steps {
                dir('backend') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Run Java') {
            steps {
                dir('backend') {
                    sh 'mvn exec:java'
                }
            }
        }

        stage('Install Node.js') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }

        stage('Run Node.js') {
            steps {
                dir('frontend') {
                    sh 'npm start'
                }
            }
        }
    }
}
